site_name: MacroDroid Wiki
site_description: Unofficial MacroDroid Documentation
site_author: JosueG28

site_favicon: assets/favicon.ico

theme:
  name: material
  logo: assets/macrodroid_icon.png
  language: en
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy
    - content.action.edit
    - search.suggest
    - search.highlight
    - i18n
  palette:
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Cambiar a tema claro
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Cambiar a tema oscuro
  font:
    text: Roboto
    code: Roboto Mono

extra_css:
  - macrodroid-colors.css
  - overrides/categorias.css

extra_javascript:
  - assets/categories.json
  - apply-colors.js

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - codehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.tasklist
  - attr_list
  - def_list
  - tables

plugins:
  - search
  - i18n:
      docs_structure: folder
      default_language: en
      languages:
        - locale: en
          name: English
          default: true
          build: true
          site_name: MacroDroid Wiki
          site_description: Unofficial MacroDroid Documentation
          site_author: JosueG28
          nav:
            - Home: index.md
            - Helper app: 
                - Download and information: helper/index.md
                - Install Universal Helper: helper/universal.md
                - Install Connectivity Helper: helper/connectivity.md
            - Hack ADB:
                - Guide: action_bñloks/index.md
            - Triggers:
                - Introduction to triggers: triggers/index.md
                - List of triggers: triggers/list.md
            - Actions:
                - Introduction to actions: actions/index.md
                - Control flow: actions/control_flow/index.md
                - Actions list: actions/list.md
            - Constraints:
                - Introduction to constraints: constraints/index.md
                - Constraints list: constraints/list.md
            - Action blocks: 
                - Introduction to the action blocks: action_blocks/index.md
            - Variables:
                - Introduction to variables: variables/index.md
            - Magic text:
                - Introduction to the Magic Text: magic_text/index.md
                - No trigger required to operate: magic_text/no_trigger/index.md
                - Trigger required to operate: magic_text/trigger_required/index.md
            - Stopwatches:
                - Introduction to stopwatches: stopwatches/index.md
            - MacroDroid log:
                - System log: macrodroid_log/system_log.md
                - User log: macrodroid_log/user_log.md
            - Import/Export:
                - Introduction: import_export/index.md

        - locale: es
          name: Español
          build: true
          site_name: MacroDroid Wiki
          site_description: Documentación no oficial de MacroDroid
          site_author: JosueG28
          nav:
            - Inicio: index.md
            - Disparadores:
                - Introducción a disparadores: triggers/index.md
            - Acciones:
                - Introducción a acciones: actions/index.md
                - Flujo de control: actions/control_flow/index.md
            - Restricciones:
                - Introducción a restricciones: constraints/index.md
            - Bloques de accion:
                - Introducción a bloques de accion: action_blocks/index.md
            - Texto mágico: 
                - Introducción al texto mágico: magic_text/index.md
                - No trigger required to operate: magic_text/no_trigger/index.md
                - Trigger required to operate: magic_text/trigger_required/index.md

extra:
  alternate:
    - name: English
      link: "/"
      lang: en
    - name: Español
      link: "/es/"
      lang: es