site_name: MacroDroid Wiki
site_description: Unofficial MacroDroid Documentation
site_author: JosueG28

theme:
  name: material
  #custom_dir: overrides/          # si usas overrides para templates
  #logo: assets/logo.svg           # pon aquí tu logo si lo tienes
  language: en

  # Paleta de colores base
  palette:
    # Modo claro
    - scheme: default
      primary: blue grey             # cambia si quieres otro color de ACENTO
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Modo oscuro
    - scheme: slate
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  # Habilita tu CSS extra con las variables de MacroDroid
  extra_css:
    - stylesheets/extra.css

  extra_javascript:
    - javascripts/section-highlights.js

  # Funcionalidades de Material for MkDocs
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy
    - content.action.edit
    - search.suggest
    - search.highlight
    - i18n

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - codehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.tasklist

plugins:
  - search
  - i18n:
      docs_structure: folder
      default_language: en
      languages:
        - locale: en
          name: English
          default: true
          build: true
          site_name: MacroDroid Wiki
          site_description: Unofficial MacroDroid Documentation
          site_author: JosueG28
          nav:
            - Home: index.md
            - Triggers:
                - Introduction to triggers: triggers/index.md
            - Actions:
                - Introduction to actions: actions/index.md
                - Control flow: actions/control_flow/index.md
                - Actions list: actions/actions_list/index.md
            - Constraints:
                - Introduction to restrictions: constraints/index.md
            - Magic text:
                - Introduction to the Magic Text: magic_text/index.md
                - No trigger required to operate: magic_text/no_trigger/index.md
                - Trigger required to operate: magic_text/trigger_required/index.md

        - locale: es
          name: Español
          build: true
          site_name: MacroDroid Wiki
          site_description: Documentación no oficial de MacroDroid
          site_author: JosueG28
          nav:
            - Inicio: index.md
            - Disparadores:
                - Introducción a disparadores: triggers/index.md
            - Acciones:
                - Introducción a acciones: actions/index.md
                - Flujo de control: actions/control_flow/index.md
            - Restricciones:
                - Introducción a restricciones: constraints/index.md
            - Texto mágico: 
                - Introducción al texto mágico: magic_text/index.md
                - No trigger required to operate: magic_text/no_trigger/index.md
                - Trigger required to operate: magic_text/trigger_required/index.md

extra:
  alternate:
    - name: English
      link: "/"     # raíz
      lang: en

    - name: Español
      link: "es/"   # /es/
      lang: es