site_name: MacroDroid Wiki
site_description: Unofficial MacroDroid Documentation
site_author: JosueG28

theme:
  name: material
  language: en
  
  # Paleta de colores base (restaurada)
  palette:
    # Modo claro
    - scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Modo oscuro
    - scheme: slate
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy
    - search.suggest
    - search.highlight
    - i18n

extra_css:
  - stylesheets/section-colors.css

extra_javascript:
  - javascripts/section-colors.js

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - codehilite
  - pymdownx.superfences

plugins:
  - search
  - i18n:
      docs_structure: folder
      default_language: en
      languages:
        - locale: en
          name: English
          default: true
          build: true
          site_name: MacroDroid Wiki
          site_description: Unofficial MacroDroid Documentation
          site_author: JosueG28
          nav:
            - Home: index.md
            - Triggers: triggers/index.md
            - Actions: actions/index.md
            - Constraints: constraints/index.md
            - Magic text: magic_text/index.md

        - locale: es
          name: Espa침ol
          build: true
          site_name: MacroDroid Wiki
          site_description: Documentaci칩n no oficial de MacroDroid
          site_author: JosueG28
          nav:
            - Inicio: index.md
            - Disparadores: triggers/index.md
            - Acciones: actions/index.md
            - Restricciones: constraints/index.md
            - Texto m치gico: magic_text/index.md

extra:
  alternate:
    - name: English
      link: "/"
      lang: en
    - name: Espa침ol
      link: "es/"
      lang: es